name: Build Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore --verbosity detailed
      
    - name: Build Debug
      run: dotnet build -c Debug --verbosity detailed
      continue-on-error: true
      
    - name: List files
      run: dir -Recurse